<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Artificial-Neural-Network-(ANN)" data-toc-modified-id="Artificial-Neural-Network-(ANN)-1">Artificial Neural Network (ANN)</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Question" data-toc-modified-id="Question-1.0.1">Question</a></span></li></ul></li><li><span><a href="#Data-Preprocessing" data-toc-modified-id="Data-Preprocessing-1.1">Data Preprocessing</a></span></li><li><span><a href="#Fixing-Categorical-Data" data-toc-modified-id="Fixing-Categorical-Data-1.2">Fixing Categorical Data</a></span></li><li><span><a href="#Splitting-into-training-and-testing-dataset." data-toc-modified-id="Splitting-into-training-and-testing-dataset.-1.3">Splitting into training and testing dataset.</a></span></li><li><span><a href="#Feature-Scaling" data-toc-modified-id="Feature-Scaling-1.4">Feature Scaling</a></span></li><li><span><a href="#Make-the-ANN" data-toc-modified-id="Make-the-ANN-1.5">Make the ANN</a></span></li><li><span><a href="#Importing-keras-libraries-and-packages" data-toc-modified-id="Importing-keras-libraries-and-packages-1.6">Importing keras libraries and packages</a></span></li><li><span><a href="#Initialising-the-ANN" data-toc-modified-id="Initialising-the-ANN-1.7">Initialising the ANN</a></span></li><li><span><a href="#Adding-the-input-layer-and-first-hidden-layer" data-toc-modified-id="Adding-the-input-layer-and-first-hidden-layer-1.8">Adding the input layer and first hidden layer</a></span></li><li><span><a href="#Output-layer" data-toc-modified-id="Output-layer-1.9">Output layer</a></span></li><li><span><a href="#Compile-the-ANN-code" data-toc-modified-id="Compile-the-ANN-code-1.10">Compile the ANN code</a></span></li><li><span><a href="#Fitting-the-ANN" data-toc-modified-id="Fitting-the-ANN-1.11">Fitting the ANN</a></span></li></ul></li><li><span><a href="#Prediction--and-evaluation-of-model" data-toc-modified-id="Prediction--and-evaluation-of-model-2">Prediction  and evaluation of model</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Predicting-the-test-set-results" data-toc-modified-id="Predicting-the-test-set-results-2.0.1">Predicting the test set results</a></span></li><li><span><a href="#Confusion-Matrix" data-toc-modified-id="Confusion-Matrix-2.0.2">Confusion Matrix</a></span></li></ul></li></ul></li></ul></div>

# Artificial Neural Network (ANN)



### Question
> A bank company sees customers leaving at an unusually higher rate. They want to know what the problem is, and they assess the problem.

>> They collected data for 10000 customers and observed them for 6 months. After the period few of them left the bank service and few stayed

**Make a model giving the bank details as which are the customers who have high chance of leaving?**
> A classification problem

## Data Preprocessing

In [36]:
# Importing the libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cross_validation import train_test_split #for splitting the dataset

from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder #for feature scaling and categorical data

from sklearn.metrics import confusion_matrix, accuracy_score


In [2]:
# import the dataset

dataset = pd.read_csv("/Users/ankitsharma/Documents/Documents/Stuff/Machine Learning/Udemy Course/Part 8 - Deep Learning/Artificial Neural Networks (ANN)/Churn_Modelling.csv")

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# feature matrix

# Independent variable which we want to include

X = dataset.iloc[:, 3:13].values #index from 3 to 12

#dependent variable

y = dataset.iloc[:, 13].values

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0])

## Fixing Categorical Data

In [10]:
#Encoding the categorical data for Independent variables

# From the dataset X, we can see that Country and Gender are in categorical form with 3 and 2 levels respectively.

#two labelencoders to be created
#For Country
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

#For Gender
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [11]:
X #female = 0 male = 1

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

* Since, our categorical variable for `country` is not ordinal i.e. France Germany and Spain are not higher than each other. So, we need to create dummy variables.

In [12]:
#create the dummy variables

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [13]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

* **To change from scientific to floating point view of data**

In [16]:
np.set_printoptions(formatter={'float_kind':'{:0.0f}'.format})

In [17]:
X

array([[1, 0, 0, ..., 1, 1, 101349],
       [0, 0, 1, ..., 0, 1, 112543],
       [1, 0, 0, ..., 1, 0, 113932],
       ..., 
       [1, 0, 0, ..., 0, 1, 42086],
       [0, 1, 0, ..., 1, 0, 92889],
       [1, 0, 0, ..., 1, 0, 38191]])

In [18]:
# removing 1 dummy variable to avoid dummy variable trap
 
X = X[:, 1:] #basically removing the 0th index

In [19]:
X


array([[0, 0, 619, ..., 1, 1, 101349],
       [0, 1, 608, ..., 0, 1, 112543],
       [0, 0, 502, ..., 1, 0, 113932],
       ..., 
       [0, 0, 709, ..., 0, 1, 42086],
       [1, 0, 772, ..., 1, 0, 92889],
       [0, 0, 792, ..., 1, 0, 38191]])

## Splitting into training and testing dataset.

8000 for training and 2000 for testing.

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [22]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
X_train

array([[-1, 2, 0, ..., 1, -1, 1],
       [2, -1, -2, ..., 1, 1, -1],
       [-1, -1, -1, ..., 1, -1, 1],
       ..., 
       [-1, -1, 1, ..., 1, -1, 1],
       [-1, 2, -1, ..., 1, 1, 1],
       [2, -1, -0, ..., 1, -1, 0]])

In [24]:
X_test

array([[2, -1, -1, ..., 1, 1, 2],
       [-1, -1, -1, ..., 1, -1, 0],
       [-1, 2, 1, ..., 1, 1, -0],
       ..., 
       [-1, 2, -1, ..., 1, -1, 1],
       [2, -1, -0, ..., 1, 1, -2],
       [2, -1, -1, ..., 1, -1, 2]])

## Make the ANN

## Importing keras libraries and packages


In [25]:
import keras

Using TensorFlow backend.


In [26]:
# import the modules

from keras.models import Sequential

from keras.layers import Dense

## Initialising the ANN

In [28]:
# neural network which will act as a classifier
classifier = Sequential()

## Adding the input layer and first hidden layer

In [30]:
classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu", input_dim = 11))

#relu (rectifier function) activation function for hidden layer
#sigmoid activation function for output layer
#11 independent variables
# 1 ouput variable

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [31]:
#Adding 2nd hidden layer

classifier.add(Dense(output_dim = 6, init = "uniform", activation = "relu"))


/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


## Output layer

In [32]:
classifier.add(Dense(output_dim = 1, init = "uniform", activation = "sigmoid"))

#output layer has only one output 
#adding the sigmoid function for the output layer

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


## Compile the ANN code

In [34]:
classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

## Fitting the ANN

In [35]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.4791 - acc: 0.7956 0s - loss: 0.4872 - acc: 0.795 - ETA: 0s - loss: 0.4851 - acc: 0.
Epoch 2/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.4260 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.4200 - acc: 0.8062
Epoch 4/100
8000/8000 [==============================] - 1s 162us/step - loss: 0.4177 - acc: 0.8232
Epoch 5/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4153 - acc: 0.8277
Epoch 6/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4138 - acc: 0.8304
Epoch 7/100
8000/8000 [==============================] - 2s 210us/step - loss: 0.4125 - acc: 0.8299
Epoch 8/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.4115 - acc: 0.8307
Epoch 9/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.4105 - acc: 0.8326
Epoch 10/100
8000/8000 [==========

# Prediction  and evaluation of model


### Predicting the test set results

In [37]:
y_pred = classifier.predict(X_test)

In [39]:
np.set_printoptions(formatter={'float_kind':'{:0.2f}'.format})

In [42]:
y_pred

array([[0.29],
       [0.32],
       [0.13],
       ..., 
       [0.21],
       [0.13],
       [0.11]], dtype=float32)

* These prediction are providing the probabilities if a customer will leave or not
* To change them in the form of true and false

In [43]:
y_pred = (y_pred > 0.5) #similar to if and else if y_pred > 0.5 return true else false

In [44]:
y_pred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

### Confusion Matrix

In [45]:
cm = confusion_matrix(y_test, y_pred)

In [46]:
cm


array([[1544,   51],
       [ 271,  134]])

In [47]:
accuracy_score(y_test, y_pred)

0.83899999999999997

In [49]:
# Manually printing the accuracy
 
(1544 + 134)/2000 #2000 testing data set

0.839